// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVYeJekLQERe9afzf_Ehsr-ErKmInNP9w',
    appId: '1:119558212353:web:64f86fc8ea23bf2fbea900',
    messagingSenderId: '119558212353',
    projectId: 'blindless-d4fb8',
    authDomain: 'blindless-d4fb8.firebaseapp.com',
    storageBucket: 'blindless-d4fb8.firebasestorage.app',
    measurementId: 'G-J7KRN0KSS2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO-jkqmzUYlqUK3v_OgJTJVJkXdtB-fsE',
    appId: '1:119558212353:android:2571fa195cf4646abea900',
    messagingSenderId: '119558212353',
    projectId: 'blindless-d4fb8',
    storageBucket: 'blindless-d4fb8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2UaS2W4vCJbbHkLOfq5QiEQG6YTYJGfA',
    appId: '1:119558212353:ios:66abe1fb8badce9cbea900',
    messagingSenderId: '119558212353',
    projectId: 'blindless-d4fb8',
    storageBucket: 'blindless-d4fb8.firebasestorage.app',
    iosBundleId: 'com.example.blindlessApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2UaS2W4vCJbbHkLOfq5QiEQG6YTYJGfA',
    appId: '1:119558212353:ios:66abe1fb8badce9cbea900',
    messagingSenderId: '119558212353',
    projectId: 'blindless-d4fb8',
    storageBucket: 'blindless-d4fb8.firebasestorage.app',
    iosBundleId: 'com.example.blindlessApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVYeJekLQERe9afzf_Ehsr-ErKmInNP9w',
    appId: '1:119558212353:web:71840a6e4d82ebdabea900',
    messagingSenderId: '119558212353',
    projectId: 'blindless-d4fb8',
    authDomain: 'blindless-d4fb8.firebaseapp.com',
    storageBucket: 'blindless-d4fb8.firebasestorage.app',
    measurementId: 'G-YNXKVP7L1G',
  );

}